### ISSUE TITLE
Error: PGOUSER environment variable not set

### ISSUE THREAD

**Issue by ccollicutt** [CrunchyData/postgres-operator-playbooks#9]
First, thanks for the updates today. :) I'm new to PGO. I've just run the playbook, and have added the environment variables that point to the various cert files. I've moved them off of /tmp though.

```
$ env | grep "^PGO\|^CO"
PGO_CA_CERT=/home/centos/pgo-config/pg-operator.crt
PGO_CLIENT_KEY=/home/centos/pgo-config/privkey.pem
PGO_CLIENT_CERT=/home/centos/pgo-config/pg-operator.crt
CO_APISERVER_URL=https://172.30.205.106:8443
```

However, running `pgo version` errors out.

```
$ pgo version
Error: PGOUSER environment variable not set
```

What else would I need to do to get `pgo version` to work? I'm guessing perhaps some minor instruction is missing from the readme. I'll keep looking but thought I'd mention it.

**Comment by ccollicutt** [comment]
Ok I see that something like this should be done, based on the username and password set in the inventory file (I'm guessing?).

```
[centos@e300k8sm ~]$ echo "<username>:<password>" > $HOME/.pgouser
[centos@e300k8sm ~]$ pgo version
pgo client version 3.5.0
pgo-apiserver version 3.5.0
```
Now `pgo version` completes.

```
$ pgo version
pgo client version 3.5.0
pgo-apiserver version 3.5.0
```

I wonder if it would be worthwhile to add that to the docs. Thanks again for the software. :)

**Comment by jasonodonnell** [comment]
Ah thanks, my environment must of had this set and was passing :)

I will add this, appreciate the report.

**Comment by jasonodonnell** [comment]
The playbooks do create the `~/.pgouser` file: https://github.com/CrunchyData/postgres-operator-playbooks/blob/master/roles/operator/tasks/main.yml#L63-L73

But the environment variable was missing from instructions.
